gero_produit:
    resource: "@GeroBundle/Controller/ProduitsController.php"
    type:     annotation

pages:
    resource: "@PagesBundle/Resources/config/routing.yml"
    prefix:   /

utilisateurs:
    resource: "@UtilisateursBundle/Resources/config/routing.yml"
    prefix:   /

gero:
    resource: "@GeroBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"