routingPanier:
  resource: "@GeroBundle/Resources/config/routing/routingPanier.yml"
  prefix: /panier

routingProduits:
  resource: "@GeroBundle/Resources/config/routing/routingProduit.yml"
  prefix: /

routingProduitAdmin:
  resource: "@GeroBundle/Resources/config/routing/routingProduitAdmin.yml"
  prefix: /admin/produit