<?php

namespace GeroWebSite\GeroBundle\Repository;

/**
 * AjoutArgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AjoutArgentRepository extends \Doctrine\ORM\EntityRepository
{
}
