<?php

namespace GeroWebSite\GeroBundle\Repository;

/**
 * ConsommeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsommeRepository extends \Doctrine\ORM\EntityRepository
{
}
