<?php

namespace GeroWebSite\GeroBundle\Repository;

/**
 * Produit_SimpleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Produit_SimpleRepository extends \Doctrine\ORM\EntityRepository
{
}
