<?php

namespace GeroWebSite\GeroBundle\Repository;

/**
 * UtilisateursSoldeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateursSoldeRepository extends \Doctrine\ORM\EntityRepository
{
}
