home:
    path:     /
    defaults: { _controller: GeroBundle:Produits:home}

produit:
    path: /produits
    defaults: {_controller: GeroBundle:Produits:produit}

presentation:
    path:     /produits/{id}
    defaults: { _controller: GeroBundle:Produits:presentation}