Panier:
    path:     /panier
    defaults: { _controller: GeroBundle:Panier:panier}

validation:
    path:     /validation
    defaults: { _controller: GeroBundle:Panier:validation}


supprimer:
    path:     /supprimer/{id}
    defaults: { _controller: GeroBundle:Panier:supprimer}


ajouter:
    path:     /ajouter/{id}
    defaults: { _controller: GeroBundle:Panier:ajouter}
    methods:  GET
